### ISSUE TITLE
issues with support for hierarchical module naming schemes in EasyBuild v1.14.0

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#1011]
This issue is intended for keeping track of the various issues in EasyBuild v1.14.0 related to support for hierarchical module naming schemes.

**Following up on the individual problems should be done in the respective issues that were opened for them (see below).**
- [x] ~~lower-level modules contain load statements for high-level modules (see #996, fix in ~~#1016~~)~~ **FIXED**
- [x] ~~`HierarchicalMNS` is incompatible with current `ictce` and `intel` toolchains (see #980, fix in ~~#983~~ and ~~#986~~, fixed in https://github.com/hpcugent/easybuild-easyconfigs/pull/1069)~~ **FIXED**
- [ ] `GCC` dependency of `icc` & `ifort` in `intel/2014b` results in extending `$MODULEPATH` with modules for GCC-based builds (resolved in `intel/2014.08` via ~~#1003~~, see https://github.com/hpcugent/easybuild-easyconfigs/pull/1014)
- [x] ~~using `--try-toolchain-version` with `--robot` and `HierarchicalMNS` fails (see #1001 + related #722, fix in #1032)~~ **FIXED**
- [x] ~~conflict specifications are not always correct for custom module naming schemes (see #994, fix in ~~#1017~~)~~ **FIXED**
- [ ] dependencies should also be resolved with subtoolchains (see #741)
- [ ] add support for only generate modules (skipping the installation) (see #998, (partial?) fix in #1018)

If you are aware of any issues not listed here, let us know.
