### ISSUE TITLE
META - parameter renaming effort

### ISSUE THREAD

**Issue by jfgrimm** [easybuilders/easybuild-framework#4563]
Meta issue to track progress on the renaming, since https://github.com/easybuilders/easybuild-framework/issues/4464 already has a lot of text in it.

* documentation
    - [ ] naming style guide
    - [ ] list of changes

* add framework support for renamed:
    - [x] [[#4511](https://github.com/easybuilders/easybuild-framework/pull/4511), [#4555](https://github.com/easybuilders/easybuild-framework/pull/4555)] easyconfig parameters, templates & constants
    - [ ] [[#4556](https://github.com/easybuilders/easybuild-framework/pull/4556)] easybuild configuration options
    - [ ] [[#4587](https://github.com/easybuilders/easybuild-framework/pull/4587)] toolchain options
    
* add parameters to be renamed to the corresponding `ALTERNATIVE_*` dicts:
    - [x] [[#4514](https://github.com/easybuilders/easybuild-framework/pull/4514)] easyconfig parameters, templates & constants
    - [ ] easybuild configuration options
    - [ ] toolchain options
    
* enhance `--fix-deprecated-easyconfigs` to update easyconfigs to use new parameters
    
* switch to new parameters in existing easyblocks/easyconfigs:
    - [ ] easyconfigs
    - [ ] easyblocks
    
* rename easyblock-specific custom parameters:
    - [ ] generic
    - [ ] other
